### PR TITLE
Eliminate fake CPUs

### PR DESCRIPTION
**Pull request by JuniorPolegato**
Eliminate fake CPUs

### CODE REVIEW

**Comment by Fred78290** [comment]
@JuniorPolegato 
What means eliminate fake CPUs?

**Comment by JuniorPolegato** [comment]
> @JuniorPolegato What means eliminate fake CPUs?

There are 2 vertical bars without update at the end of CPUs group: sys and total. I think this is a mistake.

**Comment by Fred78290** [comment]
> > @JuniorPolegato What means eliminate fake CPUs?
> 
> There are 2 vertical bars without update at the end of CPUs group: sys and total. I think this is a mistake.

Your change remove the cpu system usage in red color from vue meter.

So i don't see what you said. A screenshot with explanation?

**Comment by JuniorPolegato** [comment]
> > > @JuniorPolegato What means eliminate fake CPUs?
> > 
> > 
> > There are 2 vertical bars without update at the end of CPUs group: sys and total. I think this is a mistake.
> 
> Your change remove the cpu system usage in red color from vue meter.
> 
> So i don't see what you said. A screenshot with explanation?

Hi!
The [gnome-stats-pro extension](https://github.com/tpenguin/gnome-stats-pro) just have utilization bars per core, these 2 others bars look like 2 stopped cores, without upates.
Maybe detaching these bars and fixing updates make more sense.

**Comment by Fred78290** [comment]
> Hi!
> The [gnome-stats-pro extension](https://github.com/tpenguin/gnome-stats-pro) just have utilization bars per core, these 2 others bars look like 2 stopped cores, without upates.
> Maybe detaching these bars and fixing updates make more sense.

Theses 2 bars are showing the swp usage. So if you dont have swp, it still empty...

**Comment by JuniorPolegato** [comment]
Hi!

You can see here:

image

**Comment by Fred78290** [comment]
Seen!

**Pull request merged**
